#!/usr/bin/env python3
"""TTF/variable font -> Adafruit GFXfont header, rendered 1-bit (no antialiasing).

usage: fontgen.py FONT.ttf PX WEIGHT NAME [FIRST-LAST]   (range as hex, default 20-7E)
The '`' glyph is replaced with a degree sign, so write "10`" (see DEG in face.h).
"""
import sys
from PIL import Image, ImageDraw, ImageFont

path, px, weight, name = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
first, last = (int(x, 16) for x in (sys.argv[5] if len(sys.argv) > 5 else "20-7E").split("-"))

font = ImageFont.truetype(path, px)
try:
    font.set_variation_by_axes([weight if a.get("name", b"") in (b"Weight", "Weight") else a["default"]
                                for a in font.get_variation_axes()])
except OSError:
    pass  # static font
ascent, descent = font.getmetrics()

bits, glyphs = [], []
for code in range(first, last + 1):
    ch = "°" if chr(code) == "`" else chr(code)
    ox, oy = px, 2 * px
    img = Image.new("1", (4 * px, 4 * px), 0)
    d = ImageDraw.Draw(img)
    d.fontmode = "1"
    d.text((ox, oy), ch, font=font, fill=1, anchor="ls")
    box = img.getbbox()
    adv = round(font.getlength(ch))
    if not box:
        glyphs.append((len(bits) // 8, 0, 0, adv, 0, 0))
        continue
    x0, y0, x1, y1 = box
    offset = len(bits) // 8
    for y in range(y0, y1):
        bits += [img.getpixel((x, y)) for x in range(x0, x1)]
    bits += [0] * (-len(bits) % 8)  # each glyph starts byte-aligned
    glyphs.append((offset, x1 - x0, y1 - y0, adv, x0 - ox, y0 - oy))

data = [int("".join(map(str, bits[i:i + 8])), 2) for i in range(0, len(bits), 8)]
out = [f"// Generated by tools/fontgen.py from {path.split('/')[-1]} {px}px wght {weight}. Do not edit.",
       "#pragma once", "#include <Adafruit_GFX.h>", "",
       f"const uint8_t {name}Bitmaps[] PROGMEM = {{"]
out += ["  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + "," for i in range(0, len(data), 16)]
out += ["};", "", f"const GFXglyph {name}Glyphs[] PROGMEM = {{"]
out += [f"  {{{o}, {w}, {h}, {a}, {x}, {y}}}, // 0x{first + i:02X} {chr(first + i)!r}"
        for i, (o, w, h, a, x, y) in enumerate(glyphs)]
out += ["};", "", f"const GFXfont {name} PROGMEM = {{(uint8_t *){name}Bitmaps, (GFXglyph *){name}Glyphs, "
        f"0x{first:02X}, 0x{last:02X}, {ascent + descent}}};", ""]
open(f"src/fonts/{name}.h", "w").write("\n".join(out))
print(f"src/fonts/{name}.h: {len(data)} bytes bitmap, {len(glyphs)} glyphs")
